package Game;


public class GameEvent {
	public enum EventType {
		// TO SERVER
		USERNAME, NOT_READY, READY, CHAT, SWITCH_ACTIVE, STAND_READY, MOVE, USE_POTION, USE_MISSILE, SPELL,
		
		// TO CLIENT
		CONNECTED, USERNAME_TAKEN, PLAYER, OBSERVER, RECONNECTED, PLAYER_RECONNECTED, FULL_UPDATE, NEW_PLAYER, 
		PLAYER_LEFT, PLAYER_NOT_READY, PLAYER_PARTY, PLAYER_READY, MAP, WAITING_FOR_MAP, 
		GAME_STARTING, GAME_STARTED, NO_ACTION, START_TURN, FIELD_DISAPPEAR, POISON_DAMAGE, FIELD_DAMAGE, MONSTER_DIED, GAME_WINNER,
		PLAYER_DISCONNECTED, CHAT_MESSAGE, SET_ACTIVE, MONSTER_STAND_READY, MOVE_MONSTER, SWITCH_MONSTER, 
		MELEE, MONSTER_USE_POTION, MONSTER_USE_MISSILE, MONSTER_SPELL
	};
	
	public enum CursorDir { ON_ACTIVE, N, NE, E, SE, S, SW, W, NW };
}
